version: 2

sources:
  - name: trip_data
    description: "Raw taxi and emissions data loaded into DuckDB"
    tables:
      - name: yellow_tripdata
        description: "Yellow taxi trip data from NYC"
      - name: green_tripdata
        description: "Green taxi trip data from NYC"
      - name: vehicle_emissions
        description: "Vehicle emissions data by vehicle type"
